tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# Core application library for C
brew "glib"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Icons for the GNOME project
brew "adwaita-icon-theme"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Linux/OSX/FreeBSD resource monitor
brew "bpytop"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go dependency management tool
brew "dep"
# Modern replacement for 'ls'
brew "exa"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Terminal JSON viewer
brew "fx"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Toolkit for creating graphical user interfaces
brew "gtk+3"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Fast and multi-purpose HTTP toolkit
brew "httpx"
# Json incremental digger
brew "jid"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Rainbows and unicorns in your console!
brew "lolcat"
# Mac App Store command-line interface
brew "mas"
# Statically typed compiled systems programming language
brew "nim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Tool for creating identical machine images for multiple platforms
brew "packer"
# Command-line player for https://pandora.com
brew "pianobar"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Tool to build, change, and version infrastructure
brew "terraform"
# Simplified and community-driven man pages
brew "tldr"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Secure video conferencing app
cask "jitsi-meet"
# App to write, plan, collaborate, and get organized
cask "notion"
# Command-line shell and scripting language
cask "powershell"
# Move and resize windows with ease
cask "spectacle"
# Text editor for code, markup and prose
cask "sublime-text"
# Development environment
cask "vagrant"
# Gives Vagrant VMware plugin access to various VMware functionalities
cask "vagrant-vmware-utility"
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "Bitwarden", id: 1352778147
mas "Cardhop", id: 1290358394
mas "DaisyDisk", id: 411643860
mas "Greenshot", id: 1103915944
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "Notability", id: 360593530
mas "PDF Squeezer", id: 1502111349
mas "Slack", id: 803453959
mas "Sorted", id: 1306893526
mas "Transmit", id: 1436522307
mas "Xcode", id: 497799835
